### ISSUE TITLE
Сверстать радио-кнопки

### ISSUE THREAD

**Issue by isqua** [rockn1989/mishka#3]
**Ветка:** `issues/3`

Вот такие:

<img width="276" alt="radio" src="https://cloud.githubusercontent.com/assets/529247/19019952/a5cb5198-88a2-11e6-8a44-67fbc2fcc05c.png">

Обрати внимание, что на мобильных они мельче, чем в планшете и десктопе. Не забудь проработать состояния (см. стайлгайд). Не забудь, что может быть несколько строк текста, а может быть одна.

1. Расскажи в каментах к ишье, какие вообще нужны данные, чтобы отрисовать радиобаттон. Например, у тебя на странице пять радио. Что меняется от радио к радио?
2. Создай блок `radio` с помощью команды `make-block` (посмотри в [доке](https://github.com/CSSSR/csssr-project-template))
3. Посмотри что изменилось в проекте: `git status`.
4. Заинклюдь шаблон радио в шаблон `app/pages/demo.jade`.
5. Попробуй этот шаблон вызвать, передав туда какой-нибудь контент.
6. Посмотри в браузере, что сборка не сломалась.
7. Запили шаблон блока.
8. Запили стили блока.
9. Присылай пулл-реквест.

Для этого уже надо почитать [pugjs mixins](https://pugjs.org/language/mixins.html) и [bemto](https://github.com/kizu/bemto). И наверное захочешь ещё раз покурить [демо](https://github.com/CSSSR/csssr-project-template/tree/demo).

**Comment by rockn1989** [comment]
Чтобы сделать радиобаттон, отличный от стандартного, нужен :
1) `label`
2) внутри `label` положить `input type="radio"` + 2 тега `span`, где один это замена радиобаттона, а второй `span` для подписи

**Comment by isqua** [comment]
Вот этим как раз будет заниматься шаблон. Шаблон — это как функция в JS. Принимает всякие параметры, что-то с ними делает, потом отдаёт результат. Вот что бы ты сделал _параметрами_ радиобаттона?

**Comment by rockn1989** [comment]
Хм... если все что я описал - это уже есть в шаблоне, то в качестве аргументов передавал либо имена классов для всех элементов + текст подписи, либо только текст подписи

**Comment by isqua** [comment]
В шаблоне ничего нет, его напишешь ты. Но прежде, чем его писать, нужно придумать, что ты будешь в него передавать, а что он сделает сам.

**Comment by isqua** [comment]
Представь, что тебе нужно написать функцию `createRadioButton`, которая создаёт ДОМ-элемент для радио. Какие бы параметры ты хотел ей передавать? Что бы она делала сама?

**Comment by rockn1989** [comment]
Мне сложно словами разжевать все это, так как мысль самом не до конца ясна, по сему покажу такой вот код:

**Comment by isqua** [comment]
Зачем передавать имена классов? У тебя у всех радиобаттонов будут разные классы? Какой тогда смысл выносить в миксин? А что насчёт отправки такого радио на сервер? Каким параметром и с каким значением оно туда придёт?

**Comment by rockn1989** [comment]
Передавать можно `name` параметром и подпись
```
	mixin radio(name, someText)
		label
			input(type="radio" name=name)
			span
			span= someText

	+radio("device", "click Me")
```

**Comment by isqua** [comment]
Что тогда уйдёт на сервер? Например мне надо вот такие радио:
```
Какой Толстой умер позже остальных?

( ) Алексей Константинович
(×) Алексей Николаевич
( ) Лев Николаевич
```
чо делать?

**Comment by rockn1989** [comment]
передавать параметром еще `value`, так как именно по нему сервер будет определять что именно было выбрано

**Comment by isqua** [comment]
Окей. А как мне выбрать какой-нибудь радио по умолчанию? Чтобы пользователь заходит на страницу, а там уже предвыбрано что-нибудь?

**Comment by rockn1989** [comment]
Добавить условия в шаблон

```
	mixin radio(name,value, checked, someText)

		label
		- var check= checked || false
		if check
			input(type="radio" name=name value=value checked )
			span
			span= someText
		else
			input(type="radio" name=name value=value )
			span
			span= someText

	+radio("device","apple", "", "click Me")
```

**Comment by isqua** [comment]
Итого, видимо надо передавать четыре параметра: `name`, `value`, `checked` и `label` (`text`). Давай только передавать их не по порядку (тогда придётся помнить в каком они порядке), а объектом, тогда о порядке можно не париться. Итого, я хочу на странице demo сделать так (в дополнение к заголовку h1):

```jade

section 
  h2 Примеры радио-кнопок
  +radio-button({
    "label": "Аксессуар для интерьера",
    "name": "radiotest",
    "value": "accessory",
    "checked": true
  })
  +radio-button({
    "label": "Детская игрушка",
    "name": "radiotest",
    "value": "toy"
  })
```
Ну и чтобы работало :) Ты сначала можешь попробовать написать просто миксин, без bemto. А когда напишешь, попробовать переписать с bemto.

**Comment by rockn1989** [comment]
Просто это вот так вот
```
	mixin radio-button(data)
		label
			- var check= data.checked || false
			if check
				input(type="radio" name=data.name value=data.value checked )
				span
				span= data.label
			else
				input(type="radio" name=data.name value=data.value )
				span
				span= data.label
```
А с `bemto` ...почитать/глянуть надо. За эти 2 дня что-то очень много информации вышло, поболее чем во время интенсива :)

**Comment by isqua** [comment]
Тебе из-за чекеда весь код дублировать надо? А где классы? Стилизацию-то тоже надо делать. Давай уже в пулл-реквесте конкретный код обсуждать. В ишью достаточно слов.
